// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      // ignore: no_default_cases
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbCW3E_9osHEY0WQT1w8BI7r3znL9Ec2Y',
    appId: '1:772004513696:web:6cd2d670200cd6de9786c5',
    messagingSenderId: '772004513696',
    projectId: 'new-app-proyect',
    authDomain: 'new-app-proyect.firebaseapp.com',
    storageBucket: 'new-app-proyect.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoXRj_gnvuKb-oAhGfGzNHjHDaQkE0dKc',
    appId: '1:772004513696:android:4f6de00833e9fd979786c5',
    messagingSenderId: '772004513696',
    projectId: 'new-app-proyect',
    storageBucket: 'new-app-proyect.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk0yRFX3q5ktuFfX64-i4eyFkIlYblugE',
    appId: '1:772004513696:ios:ad2435063d1c6d589786c5',
    messagingSenderId: '772004513696',
    projectId: 'new-app-proyect',
    storageBucket: 'new-app-proyect.appspot.com',
    iosClientId:
        '772004513696-kk3tarmirk803d46hiv5dv4vpg15h8la.apps.googleusercontent.com',
    iosBundleId: 'com.newsoft.com.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBk0yRFX3q5ktuFfX64-i4eyFkIlYblugE',
    appId: '1:772004513696:ios:ad2435063d1c6d589786c5',
    messagingSenderId: '772004513696',
    projectId: 'new-app-proyect',
    storageBucket: 'new-app-proyect.appspot.com',
    iosClientId:
        '772004513696-kk3tarmirk803d46hiv5dv4vpg15h8la.apps.googleusercontent.com',
    iosBundleId: 'com.newsoft.com.app',
  );
}
